version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run: npm install yarn@latest
      - run: make install
      - run: make deploy
